### ISSUE TITLE
Mac and Linux release download links do not work

### ISSUE THREAD

**Issue by fbristow** [hyattpd/Prodigal#1]
Hello,
I'm trying to download prodigal from github here: https://github.com/hyattpd/Prodigal/releases

The Mac and Linux release links throw back Amazon AWS errors. I'm happy to build from source, but getting the binaries would be much more convenient for me.

Thanks!

**Comment by hyattpd** [comment]
Github is having issues at the moment:
https://status.github.com/messages

I'm hoping the issue with the binaries is the same as the issue with the tarballs, and everything will start working again when they fix it.  If it's still broken in 24 hours, I'll post new binaries.

**Comment by hyattpd** [comment]
OK, the issue didn't resolve itself so I removed the bad links.

I re-added the Linux binary and it seems to be working.  Will get the Mac download up tonight.

**Comment by hyattpd** [comment]
Sorry for the delays.  Replaced the Mac binary and verified everything is downloading.
