### ISSUE TITLE
numbering proteins

### ISSUE THREAD

**Issue by jeanrjc** [hyattpd/Prodigal#12]
Hi,

It's a feature proposition. (not a heavy one)
For a replicon named `myreplicon` we'll get proteins named:

```
myreplicon_1 # xxx # yyy # 1 # ID=1_1
myreplicon_2 # xxx # yyy # 1 # ID=1_2
...
myreplicon_153 # xxx # yyy # 1 # ID=1_153
myreplicon_154 # xxx # yyy # 1 # ID=1_154
```

Is it possible to format the output as follows:

```
myreplicon_001 # xxx # yyy # 1 # ID=1_001
myreplicon_002 # xxx # yyy # 1 # ID=1_002
...
myreplicon_153 # xxx # yyy # 1 # ID=1_153
myreplicon_154 # xxx # yyy # 1 # ID=1_154
```

So that when doing some analysis afterwards we can sort on the protein name ?

Currently we'd have after sorting:

```
myreplicon_1
myreplicon_153
myreplicon_154
myreplicon_2
```

You could either number with as many 0s depending on the number of protein annotated. You can alternatively assume that you'll never get replicon with more than eg. 999,999 proteins and number them like `_000001` or `_000154`. I'll tend to favor the second method to have homogeneous format across different replicons. 

Thanks

**Comment by sjackman** [comment]
I'd like this feature too.

I devised a simple scheme for naming genes called UniqTag, which uses the lexicographically smallest unique _k_-mer found in the sequence as an identifier for the gene. It's simple but makes identifiers that don't change much with reassembly or reannotation. There's a command line tool and an R package. The paper is here:
[UniqTag: Content-Derived Unique and Stable Identifiers for Gene Annotation](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0128026)

**Comment by hyattpd** [comment]
Sure, seems reasonable.

**Comment by hyattpd** [comment]
I'll add this in the Go version, easy to implement.
