### ISSUE TITLE
Unix binary provided doesn't work (wrong GLIBC)

### ISSUE THREAD

**Issue by xapple** [hyattpd/Prodigal#14]
I wanted to take prodigal out for a spin, just to see what it can do. This is what I typed:

```
$ wget https://github.com/hyattpd/Prodigal/releases/download/v2.6.2/prodigal.linux
$ chmod +x prodigal.linux
$ ./prodigal.linux -help
./prodigal.linux: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./prodigal.linux)
```

**Comment by hyattpd** [comment]
This is just due to dynamic linking.  I'll go ahead and do static linking on the provided binaries from now on, but not going to go back and change any old releases.  (Easy enough to compile from source).
