### ISSUE TITLE
Partial protein Methionine

### ISSUE THREAD

**Issue by jjkoehorst** [hyattpd/Prodigal#17]
I noticed that when you have a partial gene and the beginning of that gene is unknown the first amino acid is translated to a methionine. I noticed this as the EMBL validator started complaining. Now I am wondering wether this is biology or a bug?

**Comment by hyattpd** [comment]
It should not be doing this.  I double checked the logic and it looks fine at first glance.  It only converts to methionine if the 5' edge is complete (not partial) and considered a valid start codon for the specified genetic code.  So a TTG or GTG will be translated to methionine in either a complete gene, or a gene of type "01", i.e. one with a complete 5' edge and a partial 3'.

**Comment by hyattpd** [comment]
Does the validator complain about any GTG or TTG that gets translated to 'M'?  It may just not know alternate start codons get translated to 'M'?

**Comment by jjkoehorst** [comment]
We are using the latest prodigal just checked and this is the outcome of one protein that is giving the problems. As you can see the TTG is translated to M which should be correct but partial=10 which is not what you mentioned.

> ```
> scaffold3|size198252_1 # 3 # 413 # 1 # ID=3_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.404
> MTEQEIVRIYGMRWDIEVFFKATKSLLKLQKEVQGRSYDSLVSHTTIVFARYIVLSWQNR
> CNTDERTLGGMFYELCDELKELDWAVALQQLVEILEEALEKTSKKFKNFIKSQLQQWFAS
> LPNYIKAYLPILSCES*
> 
> scaffold3|size198252_1 # 3 # 413 # 1 # ID=3_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.404
> TTGACGGAACAGGAAATTGTCCGTATTTACGGTATGCGTTGGGACATTGAGGTGTTCTTCAAGGCGACAA
> AATCGCTTTTGAAACTGCAGAAAGAAGTGCAAGGTAGATCGTATGATTCTCTCGTCAGCCACACAACAAT
> TGTGTTCGCACGGTACATTGTGTTGTCTTGGCAGAACCGATGCAACACGGATGAGCGGACATTGGGTGGC
> ATGTTTTATGAACTTTGTGATGAATTGAAAGAACTTGATTGGGCTGTAGCATTACAGCAGTTAGTCGAAA
> TTCTTGAAGAAGCTTTGGAAAAAACATCGAAAAAATTTAAAAATTTCATCAAAAGTCAACTACAGCAATG
> GTTTGCAAGTTTGCCCAATTATATCAAGGCATACTTGCCTATTTTGAGCTGCGAAAGTTGA
> 
> 
> Online translation
> LTEQEIVRIYGMRWDIEVFFKATKSLLKLQKEVQGRSYDSLVSHTTIVFARYIVLSWQNR
> CNTDERTLGGMFYELCDELKELDWAVALQQLVEILEEALEKTSKKFKNFIKSQLQQWFAS
> LPNYIKAYLPILSCES*
> ```

**Comment by hyattpd** [comment]
That is not correct behavior.  I'll look into it and get back to you.

**Comment by hyattpd** [comment]
I still can't see a flaw in the code logic, so it has to be that the gene is somehow losing its "start type = Edge" label in the nodes list.  If you can provide an input file for testing, it would help me track this down.

**Comment by hyattpd** [comment]
Thanks for the example.  I found the bug.  Turns out I need some parentheses around one of my logic statements, so it was misevaluating my conditional (i.e. my logic was fine, but wasn't getting evaluated properly due to the order stuff was getting evaluated).  I'll push a fix shortly.

**Comment by hyattpd** [comment]
Fixed.

**Comment by philipperuiz** [comment]
Hi, We use the latest Prodigal version : Prodigal V2.6.3: February, 2016 and we still observe the same error as @jjkoehorst .

>seq1
-VLPLAFVTSISISTLHHFSFLRKEVIQPQVLLRLPCYDFTPVICPALDGSFPKVRPPALGIADFHGVTGGVYKARERIHRGVLIRDY* (biopython translation)
+MLPLAFVTSISISTLHHFSFLRKEVIQPQVLLRLPCYDFTPVICPALDGSFPKVRPPALGIADFHGVTGGVYKARERIHRGVLIRDY* (prodigal output)

>seq1
GTGCTTCCGCTTGCTTTTGTGACTTCTATTAGTATCTCTACTCTCCATCACTTCAGCTTCCTTAGAAAGGAGGTGATCCAGCCGCAGGTTCTCCTACGGCTACCTTGTTACGACTTCACCCCAGTCATCTGCCCTGCCTTAGACGGCTCCTTCCCGAAGGTTAGGCCACCGGCTTTGGGCATTGCAGACTTCCATGGTGTGACGGGCGGTGTGTACAAGGCCCGGGAACGTATTCACCGCGGCGTTCTGATCCGCGATTACTAG

We observe it for V and L.
