### ISSUE TITLE
Request: Parameter for short (< 250 bp) CDS penalty

### ISSUE THREAD

**Issue by sjackman** [hyattpd/Prodigal#2]
Hi. I'm annotating a plant plastid using Prodigal, and I found it was missing a number of short but real genes ranging in size from 90 bp to 189 bp. I found that reducing the short CDS penalty size from 250 bp to 100 bp helped rescue 6 of 9 missing short genes. Could the 250 bp size please be made a command line parameter?

See…
- Branch: https://github.com/sjackman/Prodigal/tree/short-cds-penalty
- Commit: sjackman/Prodigal@8612e36
- Related issue: https://github.com/Victorian-Bioinformatics-Consortium/prokka/issues/14

**Comment by tseemann** [comment]
+1 for making this a command line option

PS. Funny how neither of the 100 and 250 constants are divisible by 3 ;-)

**Comment by hyattpd** [comment]
Short gene prediction is the main focus of the release after the one I'm working on right now.  So I will revisit this issue then if it is still a problem.  I'm hoping I can do away with all the penalties because I will have so many signals to help predict short genes more accurately, but I'll have to test this quite a bit.

**Comment by sjackman** [comment]
Hi, @hyattpd. Is there an ETA on the short-gene feature of the next release of Prodigal? I don't mean to rush you. I'm only looking for a sense of whether I should expect to use it for this project, or proceed with some less elegant hacks.

**Comment by hyattpd** [comment]
It will be a while... no longer able to work on Prodigal full time, so only come back to it periodically now.  I'll probably just release a 3.0 with all the quality-of-life changes this fall, then worry about getting out the new version with more substantial changes to the gene prediction next year.

**Comment by sjackman** [comment]
Okay. Thanks for the update. I can sympathize with not having time to work on pet projects.
