### ISSUE TITLE
Millions of null characters (\x00) inserted into called gene

### ISSUE THREAD

**Issue by smdabdoub** [hyattpd/Prodigal#21]
In the output FASTA file from prodigal, one entry has 122 million null characters inserted into the middle of the called gene:

`[('\x00', 122748928), ('V', 7), ('A', 6), ('L', 5), ('S', 5)]`

`ENVKHIWGRAQWLMPVIPALWEAKAGGSPEVR\x00...\x00ASSLWGLALVSYVEMNESHTPVCV`

**Comment by hyattpd** [comment]
In order to tell if this is a bug, I'd need the input sequence and to know what version/OS you're using.

**Comment by smdabdoub** [comment]
Apologies, I went hunting for additional information and forgot to update this issue.

I ended up re-running prodigal on the data and the null characters disappeared. So I'm chalking it up to cosmic rays.
