### ISSUE TITLE
Minimum length of gene

### ISSUE THREAD

**Issue by ghost** [hyattpd/Prodigal#25]
As far as I understand there is no specific lower length cut-off for gene calling with prodigal, is that correct?

But you penalize genes shorter than 250 bp, as far as I can see in the code. Based on this method, what are the shortest genes which get called in general? How did you get to the specific length of 250 bp?

**Comment by ghost** [comment]
Oh, just saw that the default for min gene length is 90, is that correct?

**Comment by hyattpd** [comment]
Yes, it's 90bp.  The 250bp threshold was determined by observing a lot of annotated genomes.  Somewhere below 100aa (300bp), there needs to be a penalty to offset the high false positive rate produced by the start site score.  A good start site (w/RBS) and good coding will still easily overcome any penalties.

**Comment by ghost** [comment]
Thanks, that helped me a lot!

**Comment by DaanJansen94** [comment]
Dear, 

I just saw in the article beneath that you can adjust parameters of MetaProdigal to include ORFs >=15bp in order to also detect small proteins. How can I change the minimum gene length cutoff from 90? 

https://www.cell.com/cell/pdf/S0092-8674(19)30781-0.pdf

Thanks in advance
