### ISSUE TITLE
upper limit

### ISSUE THREAD

**Issue by raphenya** [hyattpd/Prodigal#27]
The nucleotide count for my fasta file is larger than 32000000 bp long.
Is there a better method than splitting the fasta?
Cheers.

**Comment by hyattpd** [comment]
You shouldn't need to split anything.  If it's a single genome, Prodigal will still train on the first 32MBp (which should be plenty) and then process the file as normal.  If it's a metagenome, you should be running with '-p meta' and it will process every sequence separately.

The only scenario that would cause problems is if you have a single sequence that is >32Mbp, but I'm not sure what you could be analyzing that would be this big.  If you really feel the need, you can change MAX_SEQ at the top of sequence.h to whatever value you need and recompile.
