### ISSUE TITLE
Translated peptide frame information

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [hyattpd/Prodigal#28]
Hi Team,

Sorry, if I had not noticed it correctly or actually there is no frame(1-6) information associated with the translated file. when ran prodigal on nucleotide file using below command
Command:
prodigal -i sample_input.fasta -a sample_input_tarnslated.fasta -g 11

Thanks for help
-vijay

**Comment by tseemann** [comment]
The frame might be in the `fphase` column of the GFF output file: `-f gff` ?

http://www.ensembl.org/info/website/upload/gff3.html

**Comment by narsapuramvijaykumar** [comment]
I have checked the relevant column(phase under gff file) as suggested by you. But the phase column in my case is zero ("0")  always for all coding peptides, which is not true.

Can I get any alternative solution for these..!

**Comment by hyattpd** [comment]
The phase field was designed for eukaryotic exons, which can split in the middle of codons.  Phase is meant to designate if the first base of an exon is the first/second/third base of a codon.  The first base is always the start of a codon for bacterial genes without introns or frame shifts, so "0" is always the correct value for this field.  Note that for partial genes, Prodigal always reports the first base of a codon, even if the gene runs off the edge (i.e. 2..1000, not 1..1000) (so "0" is still correct with respect to this coordinate).

What you're actually asking for is which frame relative to the beginning of the sequence the gene starts in.  Prodigal doesn't calculate this, and GFF doesn't have a field for it (it would be in the comments were it to be added).  This falls under feature requests, so I'll think about this for a new version (if other people find it useful).
