### ISSUE TITLE
Running with '-m' still predicts genes across regions of N

### ISSUE THREAD

**Issue by johnne** [hyattpd/Prodigal#30]
I'm running prodigal (Prodigal V2.6.3: February, 2016) and have contigs with some regions masked with 'N' where infernal cmscan has predicted non-coding RNAs. However, although I run prodigal with the '-m' option to "Treat runs of N as masked sequence; don't build genes across them." the output has genes predicted across those regions with protein sequences translated into stretches of 'X'. I saw that the stretches of 'N' need to be at least 50 characters and they all are but nevertheless it doesn't seem to act as a mask.

I know the '-m' option was used originally by JGI for masking, but isn't it implemented anymore in prodigal? Or am I using it wrong?

Sincerely,
John

**Comment by tseemann** [comment]
@johnne can you provide the FASTA file and the parameters you used?  I can check the code, as I use prodigal a lot and want to make sure it is working correctly.

**Comment by johnne** [comment]
[testfiles.tar.gz](https://github.com/hyattpd/Prodigal/files/1295817/testfiles.tar.gz)
@tseemann Thanks for the reply. Attaching the testfiles I'm using. I ran prodigal as:

`prodigal -i final_contigs.masked.fa -d final_contigs.masked.ffn -a final_contigs.masked.faa -o final_contigs.masked.gff -f gff -p meta -m`







`

**Comment by hyattpd** [comment]
-m is really implemented in a bad clunky way, and I don't believe it expressly forbids genes from crossing the gap (it just turns the sequence into N's).  So if there's stuff that looks like protein coding on both sides in the correct frame, and can overcome the score penalty of a bunch of N's, it can predict genes across gaps.  This -m stuff was never really intended as a permanent solution to this problem.

In the development version, I explicitly added a gap-handling mode where the user can specify the behavior upon seeing any stretch of N's (pass across, run into like scaffolds, or hard stop).  This is described in the wiki.  Unfortunately, I have no ETA for this version to be done (mostly work on plants these days, and hard to find time to come back to this and finish it... there's still a lot to do before even getting to updating the metagenomic side).

**Comment by tseemann** [comment]
@hyattpd but metagenomics is "hot" these days. do it for the plant microbiome! :)

**Comment by hyattpd** [comment]
Yes, the metagenomic version can be vastly improved and I have many ideas how to do this.  Just need to find time to work on it.

**Comment by jtamames** [comment]
Hi! This issue is still not fixed, rigth? I am masking my contigs in the places where I am predicting a RNA, for gene prediction not giving me a gene there. Somethinng like this:

>k139_29
ATNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

And I get this:
>k139_29_3-368 # 3 # 368 # -1 # ID=29_1;partial=11;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=1.000
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Besides it should skip the N's, I am puzzled on how prodigal can detect a gene there, with just two valid bases in the whole contig.

Best,
Javier

**Comment by hyattpd** [comment]
i doubt I will update -m in the 2.x Prodigal (as noted before, this is done in a better way in 3.0).

If you are masking the sequence manually, a simple trick is to begin and end the mask with TTAATTAATTAA, which inserts stop codons in all 6 frames.

**Comment by tseemann** [comment]
I used to use `NNNNNCATTCCATTCATTAATTAATTAATGAATGAATGNNNNN` as my joiner!

**Comment by Jiulong-Zhao** [comment]
> I used to use `NNNNNCATTCCATTCATTAATTAATTAATGAATGAATGNNNNN` as my joiner!

I want to know why prodigal can not predict genes across the sequence you provided. Are there some references? Thank you so much!
