### ISSUE TITLE
Compare outputs of different runs with same input data

### ISSUE THREAD

**Issue by avu0** [hyattpd/Prodigal#33]
Hi, I am writing unit tests for a script which called Prodigal. I need to compare the contents of the output files of different runs (using the same input data). However, I can't do this since the contents of the outputs differ per execution of Prodigal (same input data). How can I rectify this issue?

**Comment by tseemann** [comment]
@avu0 prodigal is a single threaded application with no random elements.  i am not sure how you can get different answers with the same input file?

```
for F in $(seq 1 100); do prodigal -i GENOME.FASTA -o $F.out ; done
```
All the files `1.out` to `100.out` will be exactly the same.  You can confirm using the `diff` or `cmp` commands.

**Comment by avu0** [comment]
Hi, I ran prodigal two different times on the same input data. When performing a diff command the output files were different. I have attached the files (input and output) for you to see.

GCF_000003135.1_ASM313v1_genomic.fna.gz - Input File

Each output file is indicated by run. All files with run1 were from the first iteration, the files with run2 are from the 2nd iteration of Prodigal. When doing a diff command for each of the files, it's clear the outputs differ. Can you please help me with this?





[GCF_000003135.1_ASM313v1_genomic.fna.gz](https://github.com/hyattpd/Prodigal/files/1448268/GCF_000003135.1_ASM313v1_genomic.fna.gz)

**Comment by avu0** [comment]
Hi @tseemann , I ran prodigal two different times on the same input data. When
performing a diff command the output files were different. I have attached
the files (input and output) for you to see.

GCF_000003135.1_ASM313v1_genomic.fna.gz - Input File

Each output file is indicated by run. All files with run1 were from the
first iteration, the files with run2 are from the 2nd iteration of Prodigal.
When doing a diff command for each of the files, it's clear the outputs
differ. Can you please help me with this? Github won't allow for me to upload files with the .faa, .gff, or .ffn extension so I uploaded them as text files. Please let me know if I can clarify anything.




[GCF_000003135.1_ASM313v1_genomic.fna.gz](https://github.com/hyattpd/Prodigal/files/1448272/GCF_000003135.1_ASM313v1_genomic.fna.gz)


[run2_GCF_000003135.1.faa.txt](https://github.com/hyattpd/Prodigal/files/1448275/run2_GCF_000003135.1.faa.txt)
[run1_GCF_000003135.1.faa.txt](https://github.com/hyattpd/Prodigal/files/1448276/run1_GCF_000003135.1.faa.txt)
[run2_GCF_000003135.1.gff.txt](https://github.com/hyattpd/Prodigal/files/1448280/run2_GCF_000003135.1.gff.txt)
[run1_GCF_000003135.1.gff.txt](https://github.com/hyattpd/Prodigal/files/1448281/run1_GCF_000003135.1.gff.txt)
[run2_GCF_000003135.1.ffn.txt](https://github.com/hyattpd/Prodigal/files/1448282/run2_GCF_000003135.1.ffn.txt)
[run1_GCF_000003135.1.ffn.txt](https://github.com/hyattpd/Prodigal/files/1448283/run1_GCF_000003135.1.ffn.txt)

**Comment by hyattpd** [comment]
Neither of the GFF files looks like valid Prodigal output.  Seqnum should increase from 1 to N, where M is the number of contigs in the file, but yours loop 1 to 3 over and over.  My guess is ran on compressed input or something.
