### ISSUE TITLE
Broken website link

### ISSUE THREAD

**Issue by yesimon** [hyattpd/Prodigal#36]
The website link in the repo description is broken: http://prodigal.ornl.gov

**Comment by jeffkimbrel** [comment]
Does anyone have a working link for a web server version of prodigal?

**Comment by udavdasha** [comment]
Sorry for the newbie question, but I cannot figure out how to download new version of the software as Windows binary (which is said to be the best intallation option). I currently have 2.6.2. Should it be on the website which is currently now working? Or is it somewhere here on Git?

**Comment by hyattpd** [comment]
Yeah, no more web site, as ORNL doesn't have any interest in supporting web servers/web sites anymore, sadly.  When I do the next version, I'll make my own web site, though I don't know if I'll have a web server (I may add web server code to the Go code, though, so people can do their own).

**Comment by lskatz** [comment]
I access the site through the web archive sometimes to get some of that text: https://web.archive.org/web/20170823035747/http://prodigal.ornl.gov/
