### ISSUE TITLE
Convert between output formats

### ISSUE THREAD

**Issue by aersoares81** [hyattpd/Prodigal#37]
Hi, I'd like to suggest a mode that converts between the output formats, like the genbank-like format, gff3, and so on.

**Comment by tseemann** [comment]
What do you mean @aersoares81  ?

```
-f:  Select output format (gbk, gff, or sco).  Default is gbk.
```

Do you mean to convert one to the other?
Do you have a good use case?

**Comment by aersoares81** [comment]
I'm sorry, it's been a while, I don't remember what I was trying to do anymore, I guess we should close this. :)
I guess I was trying to convert gbk to gff3? Like I said, don't remember anymore, I'm sorry.
