### ISSUE TITLE
Is Prodigal Still Running?

### ISSUE THREAD

**Issue by altaetran** [hyattpd/Prodigal#40]
Hi,

I noticed that the prodigal website is not available. Is the service still available, or does this indicate that prodigal should no longer be used? Thank you!

**Comment by hyattpd** [comment]
No, the ORNL web site is done (there is sadly no interest here in supporting web servers/sites/etc. for code).  When I release Radigal (Prodigal v3, whatever I wind up calling it), I'll create my own web site somewhere.
