### ISSUE TITLE
Alternate start codons

### ISSUE THREAD

**Issue by raphenya** [hyattpd/Prodigal#44]
@hyattpd 

I have the following sequence with an alternate start codon (TTG). The sequence is from E-coli.
>Sample
ATGGTCCAGCCGTGTACATGGTTCAAACACGCCAGGCATTCGAGCGAACACGCAGTGATGCCTAACCCTTCCATCGAGGGGGACGTCCAAGGGCTGGCGCCCTTGGCCGCCCCTCATGTCAAACGTTGGGCGAACCCGGAGCCTCATTAATTGTTAGCCGTTAAAATTAAGCCCTTTACCAAACCAATACTTATTATGAAAAACACAATACATATCAACTTCGCTATTTTTTTAATAATTGCAAATATTATCTACAGCAGCGCCAGTGCATCAACAGATATCTCTACTGTTGCATCTCCATTATTTGAAGGAACTGAAGGTTGTTTTTTACTTTACGATGCATCCACAAACGCTGAAATTGCTCAATTCAATAAAGCAAAGTGTGCAACGCAAATGGCACCAGATTCAACTTTCAAGATCGCATTATCACTTATGGCATTTGATGCGGAAATAATAGATCAGAAAACCATATTCAAATGGGATAAAACCCCCAAAGGAATGGAGATCTGGAACAGCAATCATACACCAAAGACGTGGATGCAATTTTCTGTTGTTTGGGTTTCGCAAGAAATAACCCAAAAAATTGGATTAAATAAAATCAAGAATTATCTCAAAGATTTTGATTATGGAAATCAAGACTTCTCTGGAGATAAAGAAAGAAACAACGGATTAACAGAAGCATGGCTCGAAAGTAGCTTAAAAATTTCACCAGAAGAACAAATTCAATTCCTGCGTAAAATTATTAATCACAATCTCCCAGTTAAAAACTCAGCCATAGAAAACACCATAGAGAACATGTATCTACAAGATCTGGATAATAGTACAAAACTGTATGGGAAAACTGGTGCAGGATTCACAGCAAATAGAACCTTACAAAACGGATGGTTTGAAGGGTTTATTATAAGCAAATCAGGACATAAATATGTTTTTGTGTCCGCACTTACAGGAAACTTGGGGTCGAATTTAACATCAAGCATAAAAGCCAAGAAAAATGCGATCACCATTCTAAACACACTAAATTTATAAAAAATCTAATGGCAAAATCGCCCAACCCTTCAATCAAGTCGGGACGGCCAAAAGCAAGCTTTTGGCTCCCCTCGCTGGCGCTCGGCGCCCCTTATTTCAAACGTTAGACGGCAAAGTCACAGACCGCGGGATCTCTTATGACCAACTACTTTGATAGCCCCTTCAAAGGCAAGCTGCTTTCTGAGCAAGTGAAGAACCCCAATATCAAAGTTGGGCGGTACAGCTATTACTCTGGCTACTATCATGGGCACTCATTCGATGACTGCGCACGGTATCTGTTTCCGGACCGTGATGACGTTGATAAGTTGATCATCGGTAGTTTCTGCTCTATCGGGAGTGGGGCTTCCTTTATCATGGCTGGCAATCAGGGGCATCGGTACGACTGGGCATCATCTTTCCCGTTCTTTTATATGCAGGAAGAACCTGCATTCTCAAGCGCACTCGATGCCTTCCAAAAAGCAGGTAATACTGTCATTGGCAATGACGTTTGGATCGGCTCTGAGGCAATGGTCATGCCCGGAATCAAGATCGGGCACGGTGCGGTGATAGGCAGCCGCTCGTTGGTGACAAAAGATGTGGGGCACTGTTGCAAAGTTAGCGATGAGGCAGCCTTTTGTCTTATTCAAAGGCCTTACATTTCAAAAACTCTGCTTACCAGGCGCATTTCGCCCAGGGGATCACCATAATAAAATGCTGAGGCCTGGC

Prodigal is only picking up ATG start codon. But when I train using E-coli genome then the alternate start codon TTG is picked up correctly and I get the complete gene. Is there a way to get the alternate start codons without training on genomes related to the query sequence?

**Comment by hyattpd** [comment]
I'm not really following what the original input is.

Generally speaking, Prodigal needs to see 20-100+ genes or so (ideally 100+) to get a good feel for start codon usage of an organism.  It needs to see a lot of genes where TTG scores higher than ATG in order to determine TTG is ok.  For TTG, in particular, in E. coli, which isn't very common, it may need to see more than that.  So, yeah, you probably need a substantial amount of sequence for it to figure this out.

Running with -p meta may also work, since it uses existing training files that are TTG-aware.

**Comment by arpcard** [comment]
>I'm not really following what the original input is.

The following contig was picked from an assembled E. coli genomes. The complete gene is in small letters. Prodigal is picking this gene as partial. Prodigal is only picking up `ATG` start, but not `TTG`.

```
>contig_from_assembled_ecoli_isolate_containing_complete_blaOXA_1_gene
ATGGTCCAGCCGTGTACATGGTTCAAACACGCCAGGCATTCGAGCGAACACGCAGTGATGCCTAACCCT
TCCATCGAGGGGGACGTCCAAGGGCTGGCGCCCTTGGCCGCCCCTCATGTCAAACGTTGGGCGAACCCG
GAGCCTCATTAAttgttagccgttaaaattaagccctttaccaaaccaatacttattatgaaaaacaca
atacatatcaacttcgctatttttttaataattgcaaatattatctacagcagcgccagtgcatcaaca
gatatctctactgttgcatctccattatttgaaggaactgaaggttgttttttactttacgatgcatcc
acaaacgctgaaattgctcaattcaataaagcaaagtgtgcaacgcaaatggcaccagattcaactttc
aagatcgcattatcacttatggcatttgatgcggaaataatagatcagaaaaccatattcaaatgggat
aaaacccccaaaggaatggagatctggaacagcaatcatacaccaaagacgtggatgcaattttctgtt
gtttgggtttcgcaagaaataacccaaaaaattggattaaataaaatcaagaattatctcaaagatttt
gattatggaaatcaagacttctctggagataaagaaagaaacaacggattaacagaagcatggctcgaa
agtagcttaaaaatttcaccagaagaacaaattcaattcctgcgtaaaattattaatcacaatctccca
gttaaaaactcagccatagaaaacaccatagagaacatgtatctacaagatctggataatagtacaaaa
ctgtatgggaaaactggtgcaggattcacagcaaatagaaccttacaaaacggatggtttgaagggttt
attataagcaaatcaggacataaatatgtttttgtgtccgcacttacaggaaacttggggtcgaattta
acatcaagcataaaagccaagaaaaatgcgatcaccattctaaacacactaaatttataaAAAATCTAA
TGGCAAAATCGCCCAACCCTTCAATCAAGTCGGGACGGCCAAAAGCAAGCTTTTGGCTCCCCTCGCTGG
CGCTCGGCGCCCCTTATTTCAAACGTTAGACGGCAAAGTCACAGACCGCGGGATCTCTTATGACCAACT
ACTTTGATAGCCCCTTCAAAGGCAAGCTGCTTTCTGAGCAAGTGAAGAACCCCAATATCAAAGTTGGGC
GGTACAGCTATTACTCTGGCTACTATCATGGGCACTCATTCGATGACTGCGCACGGTATCTGTTTCCGG
ACCGTGATGACGTTGATAAGTTGATCATCGGTAGTTTCTGCTCTATCGGGAGTGGGGCTTCCTTTATCA
TGGCTGGCAATCAGGGGCATCGGTACGACTGGGCATCATCTTTCCCGTTCTTTTATATGCAGGAAGAAC
CTGCATTCTCAAGCGCACTCGATGCCTTCCAAAAAGCAGGTAATACTGTCATTGGCAATGACGTTTGGA
TCGGCTCTGAGGCAATGGTCATGCCCGGAATCAAGATCGGGCACGGTGCGGTGATAGGCAGCCGCTCGT
TGGTGACAAAAGATGTGGGGCACTGTTGCAAAGTTAGCGATGAGGCAGCCTTTTGTCTTATTCAAAGGC
CTTACATTTCAAAAACTCTGCTTACCAGGCGCATTTCGCCCAGGGGATCACCATAATAAAATGCTGAGG
CCTGGC
```
>Running with -p meta may also work, since it uses existing training files that are TTG-aware.

The command I used for prodigal is as follows:
```juby
prodigal -i 1.fasta -a 1.fasta.proteins -o 1.fasta.coordinates -d 1.fasta.nucleotides -s 1.fasta.potential_genes -p meta
```

**Comment by hyattpd** [comment]
I looked at the input.  Of course Prodigal considers the TTG start either way.  But the metagenomic version is choosing an archaeal training file as the highest scoring (an archaea that doesn't use SD RBS motifs) instead of a file more appropriate for E. coli.  This isn't really anything wrong with the program.
  
With anonymous sequences (as in metagenomic mode), it's doing the best it can, but it will never be perfect.  As always, the best solution is to train on the genome if you know it, or longer/more sequence so it will gravitate to the right training file in metagenomic mode.

**Comment by arpcard** [comment]
What is the limit on the training sets? Can I combine multiple genomes from different species into one training file?
