### ISSUE TITLE
prodigal 3 not predicting any genes in anon mode

### ISSUE THREAD

**Issue by mhuntemann** [hyattpd/Prodigal#45]
Hi!

Is anyone running the rc.1 version of prodigal 3 successfully on metagenomes?
It works fine for me on isolates (first training and then normal mode).
But when I run it on fasta file containing a metagenomic assembly and switch to --mode anon (also tried -p meta) no genes get predicted at all.
Prodigal 2.6.3 predicts plenty of genes though (with -p meta).
Here's an example with the shortest sequence out of the file for testing purposes:
```bash
marcelh@dint05 -> cat test.fna 
>test_seq
GGATGAGCCAGTGGCTGATCAGCGGTTGGCGCGGGTACCGACCACTTCGATCTCGACGCG
GCGGTTCTTGGCGCGACCTTCTTTGGTGCGGTTGTCAGCGATGGGCTGCTTCTCGCCCTT
GCCTTCGGTGTAGATGCGGTTTTTCTCGATGCCCTTGCTGACCAAATAGGCCTTCACGGC
TTCGGAACGACGCACCGACA

marcelh@dint05 -> $OMICS/bin/prodigal -p meta -i test.fna 
-------------------------------------
PRODIGAL v2.6.3 [February, 2016] 
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Metagenomic, Phase:  Training
Initializing training files...done!
-------------------------------------
Request:  Metagenomic, Phase:  Gene Finding
Finding genes in sequence #1 (200 bp)...done!
DEFINITION  seqnum=1;seqlen=200;seqhdr="test_seq";version=Prodigal.v2.6.3;run_type=Metagenomic;model="25|Marinobacter_aquaeolei_VT8|B|57.3|11|1";gc_cont=57.30;transl_table=11;uses_sd=1
FEATURES             Location/Qualifiers
     CDS             complement(19..>198)
                     /note="ID=1_1;partial=01;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.600;conf=99.91;score=30.71;cscore=27.49;sscore=3.22;rscore=0.00;uscore=0.00;tscore=3.22;"
//

marcelh@dint05 -> $OMICS/bin/prodigal3 --mode anon -i test.fna 
-------------------------------------
PRODIGAL v3.0.0-rc.1 [February, 2016]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Mode: Anonymous, Phase: Training
Initializing preset training files...done.
-------------------------------------
Mode: Anonymous, Phase: Gene Finding
Finding genes in sequence #1 (200 bp)...done.
DEFINITION  seqnum=1;seqlen=200;seqhdr="test_seq";version=Prodigal.v3.0.0-rc.1;run_type=Anonymous;model="0|Mycoplasma_bovis_PG45|B|29.3|0|0";gc_cont=0.00;transl_table=0;uses_sd=0
FEATURES             Location/Qualifiers
//
```

It basically looks like this for every contig in the file. Not a single gene gets predicted.
Is anyone experiencing the same issue?

Thanks,
Marcel

**Comment by hyattpd** [comment]
Prodigal 3 is very much a work in progress; I wouldn't advise anyone to be using it for anything.  I was in the middle of the regular gene prediction part (it's still unfinished), and the metagenome part has been disabled (since it has to be totally redone for the new training file scheme).

**Comment by mhuntemann** [comment]
Thanks for the quick reply!
Is there a timeline for when the new metagenome mode will be enabled again.
Also is there a difference in the training/normal mode between version 2 and 3?
Meaning, while I'll still have to run 2.6.3 for the metagenomes, would isolate predictions be improved if I switch to v3-rc.1 or is that unfinished as well?
Thanks,
Marcel

**Comment by hyattpd** [comment]
No, I have no timeline for Prodigal 3.  Hopefully I will find time to complete it this year.

Yes, there will be lots of differences in the regular gene prediction between 2 and 3.

You should not run the 3.x development versions on anything yet.  I'll post something if they ever get to the point they are ready for testing.
