### ISSUE TITLE
free(): invalid pointer: 0x00007f8b8602b010

### ISSUE THREAD

**Issue by avu0** [hyattpd/Prodigal#46]
Hi, I've posted about this issue before and I'm hoping someone can help clarify this recurring issue. 

My team modified node.h in order to better support peptide prediction (we simply redefined the MIN_EDGE_GENE and MIN_GENE variable), please see below the diff output to see details, with our changes at the bottom. 

----------------------------
# Changes made by TW on December 14th 2016
# Reduced the min gene length to support peptide prediction

diff ../2.6.3/node.h ./node.h
30,31c30,31
< #define MIN_GENE 90
< #define MIN_EDGE_GENE 60
---
> #define MIN_GENE 30
> #define MIN_EDGE_GENE 30
----------------------------

When running the following command on the fasta file attached (please make note that github does not support the .fasta extension, so I uploaded this file as a .txt file)
[problem_chunk.04.fasta.txt](https://github.com/hyattpd/Prodigal/files/2129392/problem_chunk.04.fasta.txt)
, we run into this "invalid pointer" error (screenshot attached). It is important to note that 1) this error only occurs when we run our modified node.h, and it does work when we use the original,unmodified codebase and 2) the fasta file attached is only a chunk of a larger file, but we were able to identify that this particular chunk (file attached) is the cause of the error. Output files are created, and I have attached them below.

command: /path/to/modifiedprodigal -i problem_chunk.04.fasta -a 4.tmp.faa -d 4.tmp.fna -o 4.tmp.gff -f gff -p meta -c -m -q

Please let me know if anyone has anything that can help us verify the root of this issue. Thanks in advance. 

![screen shot 2018-06-22 at 4 18 00 pm](https://user-images.githubusercontent.com/33297960/41802760-09a435d4-7638-11e8-81ab-a785f89b11f0.png)

[4.tmp.faa.txt](https://github.com/hyattpd/Prodigal/files/2129398/4.tmp.faa.txt)
[4.tmp.fna.txt](https://github.com/hyattpd/Prodigal/files/2129399/4.tmp.fna.txt)
[4.tmp.gff.txt](https://github.com/hyattpd/Prodigal/files/2129400/4.tmp.gff.txt)

**Comment by avu0** [comment]
This is a problem for our production pipeline because prodigal stalls on this error instead of exiting.

**Comment by hyattpd** [comment]
This isn't really a bug.  Prodigal is just not intended to be used on things that small.

The problem comes because microbial genes can overlap.  If you set the minimum gene size below the overlap size , this will lead to fatal errors.

You can try setting the minimum same-strand overlap to be less than 30.  Maybe it will work.

It's a good thing to add to the documentation, though.

**Comment by hyattpd** [comment]
Just to be explicit, you would need to change MAX_SAM_OVLP to be <= the gene size.
