### ISSUE TITLE
Annotating vertebrate mitochondrial genomes

### ISSUE THREAD

**Issue by sjackman** [hyattpd/Prodigal#47]
Vertebrate mitochondrial genomes use the genetic code 2. See https://en.wikipedia.org/wiki/Vertebrate_mitochondrial_code
They're also only 16 kbp, so less than Prodigal's threshold of 20 kbp, so must be run in `-p meta` mode. `-p meta` mode uses a database that include genetic codes 4 and 11, but not 2. See also the related issues #19 and #22.
Is there any workaround to use genetic code 2 on small sequences? One thought is that I could download a bunch of vertebrate mitochondrial genomes, add them to my FASTA file, and annotate the whole thing.

**Comment by tseemann** [comment]
Just put *duplicates* of your mtDNA genome in the input file with dummy names?

But adding other related mtDNA genomes might actually help it train the model?

Or build a model first?
```
         -n:  Bypass Shine-Dalgarno trainer and force a full motif scan.
         -t:  Write a training file (if none exists); otherwise, read and use
              the specified training file.
```

**Comment by sjackman** [comment]
Oh yeah totally. Building a training file on all the animal mitochondria in RefSeq would be pretty straight forward.

**Comment by hyattpd** [comment]
I'll ponder how to solve this issue in future versions.  My current plan is to allow the user to specify genetic codes for metagenomic mode in comma-delimited fashion.  However, it's a bit tricky to have models built for genetic codes besides 4, 11, and 25.

I may make some kind of lightweight coding prediction mode that doesn't focus on getting starts right, but can at least find reasonable coding/ORF boundaries in 10kb sequences, etc. (10kb was always enough to train coding, but not start sites).
