### ISSUE TITLE
Alternative start codons (annotating plant mitochondrial genomes)

### ISSUE THREAD

**Issue by sjackman** [hyattpd/Prodigal#48]
Plant mitochondrial genomes use the standard genetic code 1, mostly. There's two exceptions.

- AUG start codons are used primarily
- ACG codon is frequently edited to AUG via C-to-U RNA editing
- GUG alternative start codon is used by two genes (*rpl16* and *rps19*)
- GCG codon may be edited to a GUG alternative start codon via C-to-U RNA editing

Is there an option to specify a list of start codons?

**Comment by hyattpd** [comment]
Not currently.  Glimmer can do this.  Maybe I'll add it in a future version, shouldn't be too difficult.

**Comment by sjackman** [comment]
That'd be great. Thanks, Doug! And Prodigal will learn the frequency of these start codons on its own?
