### ISSUE TITLE
tmp filename collision

### ISSUE THREAD

**Issue by nigiord** [hyattpd/Prodigal#49]
Hi there, 

I've been using Prodigal V2.6.3 on a cluster to predict CDS in parallel on a large number of genomes (>10k, 50 jobs in parallel). Unfortunately after some time, one of the job inevitably fails with the error:

`Could not delete tmp file tmp.prodigal.stdin.xxxxx.`

with xxxxx a random number. This file is indeed no longer present when the job exits. I looked at how this filename is chosen in the code source, and it seems to use the PID of the process:

https://github.com/hyattpd/Prodigal/blob/GoogleImport/main.c#L95-L97
```C
/* Filename for input copy if needed */
pid = getpid();
sprintf(input_copy, "tmp.prodigal.stdin.%d", pid);
```

It is hard to confirm, but I suspect this problem arises when two jobs happen to use the same PID at the same time on two different nodes: the tmp file is transparently overwritten and then deleted by the first job to finish, the second job failing to delete it afterwards. I can just ignore those errors and relaunch the analysis for the few failed jobs, but If this file is indeed transparently overwritten, there could be a bigger problem due to the collision. If the timing is unfortunate, some of the prodigal results could not correspond to the original fasta that was piped inside the command (if the job is the first to finish, it exits normally, and I have no way to know a filename collision occurred).

Would it be possible to add a command line option to allow the user to specify the location or name of the temporary file? This should also improve performance on clusters by using local filesystem on each node.

Alternatively, Prodigal could check if the tmp file already exists, and exit with an error before transparently overwriting it.

Cheers,
Nils

**Comment by hyattpd** [comment]
These are all good suggestions.  I should note that Prodigal only creates a temporary file if input is piped in (since it fseeks in the file, so has to copy the input if it's piped), so one way to avoid this would be to create input files for Prodigal instead of piping input to the program.

**Comment by bkille** [comment]
What about simply making the temp file name something more unique? i.e. if you could use the node name in addition to the pid.

**Comment by hyattpd** [comment]
This issue will be addressed in the Go version (there won't be a tmp file created).

**Comment by tseemann** [comment]
The standard safe way is to use `man 3 mktemp`:

```
NAME
       mktemp - make a unique temporary filename

SYNOPSIS
       #include <stdlib.h>

       char *mktemp(char *template);

   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       mktemp():
           Since glibc 2.12:
               _BSD_SOURCE || _SVID_SOURCE ||
                   (_XOPEN_SOURCE >= 500 ||
                        _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED) &&
                   !(_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600)
           Before glibc 2.12:
               _BSD_SOURCE || _SVID_SOURCE || _XOPEN_SOURCE >= 500 ||
               _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED

DESCRIPTION
       The mktemp() function generates a unique temporary filename from template.  The last six
       characters  of  template  must be XXXXXX and these are replaced with a string that makes
       the filename unique.  Since it will be modified, template must not be a string constant,
       but should be declared as a character array.
```
