### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by jeanrjc** [hyattpd/Prodigal#5]
Hi, 

I have a segmentation fault issue with some genomes as in here : https://code.google.com/p/prodigal/issues/detail?id=4

**version used** : Prodigal V2.6.1: July, 2013
Downloaded from : https://github.com/hyattpd/Prodigal/releases/download/v2.6.1/prodigal.macosx

**computer used**: Mac Pro mid 2012 with OSX 10.8.5
#### Step to reproduce the error:
1. Download fasta file from: 
   - http://www.ncbi.nlm.nih.gov/nuccore/665822167 
   - http://www.ncbi.nlm.nih.gov/nuccore/545627323
2. rename files KJ484629.fst and KC340960.fst respectively
3. run the following command:
   
   `prodigal -i KJ484629.fst`

it outputs:

```
-------------------------------------
PRODIGAL v2.6.1 [July, 2013]         
Univ of Tenn / Oak Ridge National Lab
Doug Hyatt, Loren Hauser, et al.     
-------------------------------------
Request:  Single Genome, Phase:  Training
Reading in the sequence(s) to train...112671 bp seq created, 50.70 pct GC
Locating all potential starts and stops...5798 nodes
Looking for GC bias in different frames...frame bias scores: 1.73 0.34 0.93
Building initial set of genes to train from...done!
Creating coding model and scoring nodes...done!
Examining upstream regions and training starts...Segmentation fault: 11
```

Same for KC340960.fst

NB: 
    - Both sequences are composed of ATGC characters exclusively
    - when running the following command, it works: 

 `prodigal -p meta -i KJ484629.fst`

Is there something I can do to make it work ? (given that it works for most of the genome I'm using, and some are about the same size) 
Or is this a known bug that should be fixed ?

Thanks

**Comment by hyattpd** [comment]
Thanks, I'll look into it on my MacBook and see if I get the bug.  

Mac binaries are very picky and are often not backwards-compatible (I have no solution for this, other than putting a ton of individual binaries up for release).  My first suggestion would be to try compiling the code directly for your system and see if it works.

**Comment by hyattpd** [comment]
This bug is not related to issues with the binary.  I compiled myself on MacBook and am getting seg faults.  Trying to pin down what's causing it now.

**Comment by hyattpd** [comment]
Fixed and committed the changes, but will continue to test for a few days before releasing a 2.6.2.
