### ISSUE TITLE
Performance impacted by word wrap length

### ISSUE THREAD

**Issue by aaronmussig** [hyattpd/Prodigal#52]
Hi,

I've noticed that the performance of Prodigal is greatly impacted by the word wrap length of the input FASTA file. An input file without any word wrapping takes almost double the time of one wrapped under 1000 characters.

I've observed this on multiple genomes, however, these results are from [GCF_000754115.1_ASM75411v1](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/754/115/GCF_000754115.1_ASM75411v1) with `n=20` replicates at word wrap lengths of: `[1, 5, 10, 20, 40, 80, 150, 300, 500, 1000, 3000, 5000, 10000, 15000, 20000, 50000, 100000, 200000, 300000, 400000, 500000]`. Input was read from stdin.

![image](https://user-images.githubusercontent.com/30012322/56999779-f7323b00-6bf3-11e9-99fa-8db369c1b469.png)

I'd like to suggest forcefully word-wrapping user input, or adding a note to the documentation that the input should be strictly wrapped at 80 characters.

Thanks,
Aaron

**Comment by hyattpd** [comment]
Yeah, I need to revisit lots of basic things with file reading.  Thanks.

**Comment by tseemann** [comment]
I think Prodigal shouldn't work with lines > 10,000 bytes long?

https://github.com/hyattpd/Prodigal/search?q=MAX_LINE&unscoped_q=MAX_LINE

**Comment by hyattpd** [comment]
Yeah, it isn't something I plan on addressing in this iteration (and easily fixed by conversion to <10kb line lengths), but the Go version will handle all this gracefully.  In the old days of 2007 (lol), everyone did FASTA with 70-80bp line lengths.

**Comment by tseemann** [comment]
Yeah, 60 or 70 is the NCBI standard.

Wanted it to print out correctly on a 80 column dot matrix printer or readable on an 80x25 VT100 terminal :-)
