### ISSUE TITLE
percent of genes predicted in a metagenome?

### ISSUE THREAD

**Issue by Jigyasa3** [hyattpd/Prodigal#53]
Is it possible to do something like- (no.of protein-coding genes/no.of contigs in a metagenome)*100 = to get the percent of genes predicted in a metagenome?

Would this help make sense of how many genes were predicted in total, and compare it among samples?

**Comment by sfehrmann** [comment]
To increase your chances for a meaningfull reply you might be better off posting this question to a more general forum like biostars, or seqanswers. 

In a nutshell I don't think it is very meaningful, it depends to much on variation in microbiome composition. Look into busco and checkm to assess genome completeness, which might be easier to compare

**Comment by tseemann** [comment]
I agree with @Carambakaracho - it does not make much sense.
The fragmented nature of illumina metagenome assemblies makes estimating gene content very challenging.

**Comment by tseemann** [comment]
@Jigyasa3 can you please close this issue?
