### ISSUE TITLE
Sequence too long (max 32000000 permitted).

### ISSUE THREAD

**Issue by faylward** [hyattpd/Prodigal#54]
I'm trying to run Prodigal on a very large genome and I keep getting this error. Is there a way to run the algorithm on very large contigs?

**Comment by tseemann** [comment]
You need to edit this line in the source code and manually recompile:

https://github.com/hyattpd/Prodigal/blob/9b74af5dd408bae27579a78d33aa1a5db48871b4/sequence.h#L32

**Comment by hyattpd** [comment]
Yeah.... I'm kind of curious how you could ever have a single genome this big that Prodigal actually works on, since the biggest bacterial genome is still only like 13 million bp or something?  Anyway...

**Comment by faylward** [comment]
Thanks for the tip! I am using Prodigal for non-canonical purposes (i.e., non-bacterial genomes) so this comes up every now and again for me. I understand this isn't the intended purpose of this tool, however, and that it is not an issue for regular prokaryotic genomes.

**Comment by hyattpd** [comment]
Yeah, this won't be an issue in the Go version (won't be arbitrary limits on memory, size, etc.)
