### ISSUE TITLE
Unsafe code

### ISSUE THREAD

**Issue by danilexn** [hyattpd/Prodigal#56]
It is not a critical issue but some parts of the code, such as argument parsing in main.c, may be unsafe due to the usage of _strcmp_ and _atoi_. Also, _strcpy_ during memory allocation. Alternatives already exist and, in my opinion, should be used, instead. 

D.

**Comment by hyattpd** [comment]
Thanks, this code is kind of old and due for such updates.

**Comment by hyattpd** [comment]
I won't be addressing this in the C code.  The next version is written in Go, so it will be memory safe.
