### ISSUE TITLE
gene length cutoff

### ISSUE THREAD

**Issue by DaanJansen94** [hyattpd/Prodigal#59]
Dear,

I just saw in the article beneath that you can adjust parameters of MetaProdigal to include ORFs >=15bp in order to also detect small proteins. How can I change the minimum gene length cutoff from 90?

https://www.cell.com/cell/pdf/S0092-8674(19)30781-0.pdf

Thanks in advance

**Comment by tseemann** [comment]
I think you need to manually recompile the source code and edit the constants here:

https://github.com/hyattpd/Prodigal/blob/fe80417640fe00a35dc0b5d771c6c75f4403a4d0/node.h#L29-L37s

**Comment by hyattpd** [comment]
I'm not 100% sure how they did this.  You have to be careful.  If you reduce the minimum gene size below the minimum gene overlap size, this can create cycles in the dynamic programming graph that crash the program.  They may have made it so genes couldn't overlap more than 5bp or so.

**Comment by DaanJansen94** [comment]
Thank you! I will look into it
