### ISSUE TITLE
Binaries for version 2.6.2

### ISSUE THREAD

**Issue by tseemann** [hyattpd/Prodigal#6]
Doug,

I managed to compile 2.6.2 on Linux for table 25 support for Prokka.

Will you eventually provide a Mac OS X and Linux binary and a 2.6.2 tagged release?

Torsten

**Comment by hyattpd** [comment]
Yes.  Just need to finish some testing on Windows.

**Comment by tseemann** [comment]
Out of personal interest, what software on Windows depends on Prodigal.exe ?

**Comment by hyattpd** [comment]
None as far as I know, but the Windows binary was always a popular download
at the Google Code site (I was surprised by this, but guess some people
found it useful).  Supporting Windows isn't a big priority, and I don't do
much testing other than to make sure it runs on basic test sequences and
produces the right results.
