### ISSUE TITLE
Twitter asks if this project is still alive

### ISSUE THREAD

**Issue by tseemann** [hyattpd/Prodigal#60]
https://twitter.com/TSBSchm/status/1170643615825190913

```
Hey #bioinformatics & #metagenomics Twitter!
I have a question about gene calling. It seems like #prodigal by @doug_hyatt
 hasn't been updated since v2.6.3 (Feb 2016), and v3 probably 
won't ever happen. Is the tool dead? Did someone else take over? 
What are good alternatives?
8:22 PM · Sep 8, 2019·Twitter Web App
```

**Comment by hyattpd** [comment]
No, it isn't dead, though the C codebase is (writing Prodigal 3 in Go, not sure if will add a branch here or just do a new repo).

**Comment by oschwengers** [comment]
Very good news and thanks a lot for the effort!
Any idea when you might be able to show a first prototype?

**Comment by hyattpd** [comment]
As soon as I have functional single genome gene prediction, I'll open it up for testing.  Metagenomic will likely take a bit longer, as I'm focusing on a totally different approach there for Prodigal 3.

**Comment by tseemann** [comment]
If you change the interface please don't call it `prodigal` - It will break so much code.
Maybe a new repo - perhaps `prodiGOl` ?

**Comment by hyattpd** [comment]
Ultimately I'd like to do eukaryotic genefinding also, so the "pro" part no longer fits anyway.  My current code name for the project is "radigal".
