### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by lz870718** [hyattpd/Prodigal#70]
Dear Doug,

I was following the instruction of Installing on Generic Unix.

Everything went through. But then when I type in prodigal -h.
An error poped up as below:
prodigal: command not found

Could you provide any suggestions?
Best,
Zhi

**Comment by hyattpd** [comment]
You're probably using bash, which doesn't include your current directory in $PATH.

Try `./prodigal`

**Comment by tseemann** [comment]
@lz870718 can you close this issue if you solved it?
if not, try using `brew` or `conda` to install bioinformatics tools.
